#!/usr/bin/env bash
set -euo pipefail

# resolve the real directory of this script (follow symlinks)
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
EXEC_DIRNAME="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# run the container
export APPTAINER_BIND="/raw_data,/databases,/projects"
apptainer run -nvccli "$EXEC_DIRNAME/esmfold.sif" "$@"
